// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe5NxjHl3NQdR7rgzPolB4QIeMEMaXx54',
    appId: '1:1029992422023:web:b96ca0affb4f01aa6f3622',
    messagingSenderId: '1029992422023',
    projectId: 'push-notification-64516',
    authDomain: 'push-notification-64516.firebaseapp.com',
    storageBucket: 'push-notification-64516.firebasestorage.app',
    measurementId: 'G-C1J0EEF21B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeNaStuAjlbUdHtBoo-vKNFEMXVURTGc8',
    appId: '1:1029992422023:android:e1173ec9b575e8e36f3622',
    messagingSenderId: '1029992422023',
    projectId: 'push-notification-64516',
    storageBucket: 'push-notification-64516.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBudYmcpiKaGET0BQQ7QxoPRAZx5-U7f4E',
    appId: '1:1029992422023:ios:95e5a903d293a9d06f3622',
    messagingSenderId: '1029992422023',
    projectId: 'push-notification-64516',
    storageBucket: 'push-notification-64516.firebasestorage.app',
    iosBundleId: 'com.example.apiProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBudYmcpiKaGET0BQQ7QxoPRAZx5-U7f4E',
    appId: '1:1029992422023:ios:95e5a903d293a9d06f3622',
    messagingSenderId: '1029992422023',
    projectId: 'push-notification-64516',
    storageBucket: 'push-notification-64516.firebasestorage.app',
    iosBundleId: 'com.example.apiProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe5NxjHl3NQdR7rgzPolB4QIeMEMaXx54',
    appId: '1:1029992422023:web:c62ba077b9c9b3cd6f3622',
    messagingSenderId: '1029992422023',
    projectId: 'push-notification-64516',
    authDomain: 'push-notification-64516.firebaseapp.com',
    storageBucket: 'push-notification-64516.firebasestorage.app',
    measurementId: 'G-90ZKBHB01Y',
  );
}
